language: java
jdk: openjdk8
branches:
  only:
  - master
  - "/.*-[0-9]+\\..*/"
install: true
script: ".travis/build.sh"
cache:
  directories:
  - "~/.m2/repository"
  - "~/miniconda"
env:
  global:
  - secure: bM/ROC4gfw5dwe7hvcpdFTNBRx51wIvQ+atUPhf9jZjBRidI5Wr0Rhsc30HUAF0sWh4tw2qkCjPAioC/84jp2tVqUXM0PqiElLunVdf6ooJ09uBkTr3nUTdSWflEpKqrI4DPfBS317Xoj26GdWu6YaPLlpQDIPMgdMjZG9fUJRE=
  - secure: kJfRO6xMrxvCZoohUdsZHH/hTT2QwPHFG4FLnPTfFtdESS/xjscsYST90vp2qbdsv0RkcXSeA87aNgxoMj8IfDibLJwZasVXn0WybS3nOmguIzg3pqtALdpGJtdZK+WyqtkWzDGzngqcFbyQBFbYU1CjOrHV5Mx6TESH4dtwsfw=
